const ACTION_TYPES = {
  LOAD_MOVIES: "LOAD_MOVIES",
  LOAD_MOVIES_SUCCESS: "LOAD_MOVIES_SUCCESS",
  LOAD_MOVIES_ERROR: "LOAD_MOVIES_ERROR",
  SEARCH_BY: "SEARCH_BY",
  SORT_MOVIES: "SORT_MOVIES",
  SEARCH_MOVIE_CHANGE: "SEARCH_MOVIE_CHANGE",
  SELECT_MOVIE: "SELECT_MOVIE",
  CLEAR_STORE: "CLEAR_STORE",
  PERSIST_LAST_SEARCH_PHRASE: "PERSIST_LAST_SEARCH_PHRASE",
  LOAD_MOVIE_DETAILS_SUCCESS: "LOAD_MOVIE_DETAILS_SUCCESS",
}

export default ACTION_TYPES;
