const ACTION_TYPES = {
  LOAD_MOVIES: "LOAD_MOVIES",
  LOAD_MOVIES_SUCCESS: "LOAD_MOVIES_SUCCESS",
  LOAD_MOVIES_ERROR: "LOAD_MOVIES_ERROR",
  SEARCH_BY: "SEARCH_BY",
  SORT_MOVIES: "SORT_MOVIES",
  SEARCH_MOVIE_CHANGE: "SEARCH_MOVIE_CHANGE"
}

export default ACTION_TYPES;
